version: '3'
services:
  web:
    build: ./angular-app
    ports: 
    - "80:80"
    links: 
    - node
    volumes:
    - "/c/Users/moein/mean-docker-compose/angular-app/dist:/usr/share/nginx/html"
  node:
    build: ./node-app
    ports:
    - "3000:3000"
    links:
    - mongo
    volumes:
    - "/c/Users/moein/mean-docker-compose/node-app:/src"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
